# Only test the currently used features and
# display them.
FEATURE_TESTS ?= libelf lzma zlib btf-vmlinux cplus-demangle cxa-demangle libtcmalloc
FEATURE_DISPLAY := $(FEATURE_TESTS) demangle
FEATURE_GROUP_MEMBERS-demangle = cplus-demangle cxa-demangle
include $(srctree)/build/Makefile.feature

$(shell printf "" > $(OUTPUT).config-detected)
detected     = $(shell echo "$(1)=y"       >> $(OUTPUT).config-detected)
detected_var = $(shell echo "$(1)=$($(1))" >> $(OUTPUT).config-detected)
detected_override = $(shell echo "override $(1)=y" >> $(OUTPUT).config-detected)

################################

ifeq ($(feature-libelf), 1)
    $(call detected,CONFIG_LIBELF)
else
    $(error ERROR: No libelf found. Please install libelf-dev, libelf-devel, elfutils-libelf-devel.)
endif

ifeq ($(feature-lzma), 1)
    override CFLAGS += -DHAVE_LZMA_SUPPORT
    override CXXFLAGS += -DHAVE_LZMA_SUPPORT
    $(call detected,CONFIG_LZMA)
else
    $(warning No liblzma found, disables MiniDebugInfo decompression, please install xz-devel/liblzma-dev)
endif

ifeq ($(feature-zlib), 1)
    $(call detected,CONFIG_ZLIB)
endif

ifeq ($(feature-btf-vmlinux), 1)
    override CFLAGS += -DCONFIG_LIBBPF
    # Overrides the make command line option
    # `make CONFIG_LIBBPF=1`.
    $(call detected_override,CONFIG_LIBBPF)
endif

ifeq ($(feature-cplus-demangle), 1)
    override CFLAGS += -DHAVE_CPLUS_DEMANGLE_SUPPORT
    override CXXFLAGS += -DHAVE_CPLUS_DEMANGLE_SUPPORT
    $(call detected,CONFIG_CPLUS_DEMANGLE)
else
    ifeq ($(feature-cxa-demangle), 1)
        override CFLAGS += -DHAVE_CXA_DEMANGLE_SUPPORT
        override CXXFLAGS += -DHAVE_CXA_DEMANGLE_SUPPORT
        $(call detected,CONFIG_CXX_DEMANGLE)
    endif
endif

ifeq ($(feature-libtcmalloc), 1)
    override CFLAGS += -DHAVE_LIBTCMALLOC
    override CXXFLAGS += -DHAVE_LIBTCMALLOC
    $(call detected,CONFIG_LIBTCMALLOC)
endif
