__SYSCALL(0, restart_syscall)
__SYSCALL(1, exit)
__SYSCALL(2, fork)
__SYSCALL(3, read)
__SYSCALL(4, write)
__SYSCALL_WITH_COMPAT(5, open, compat_sys_open)
__SYSCALL(6, close)
__SYSCALL(7, waitpid)
__SYSCALL(8, creat)
__SYSCALL(9, link)
__SYSCALL(10, unlink)
__SYSCALL_WITH_COMPAT(11, execve, compat_sys_execve)
__SYSCALL(12, chdir)
__SYSCALL(13, time)
__SYSCALL(14, mknod)
__SYSCALL(15, chmod)
__SYSCALL(16, lchown)
__SYSCALL(18, oldstat)
__SYSCALL_WITH_COMPAT(19, lseek, compat_sys_lseek)
__SYSCALL(20, getpid)
__SYSCALL(21, mount)
__SYSCALL(22, umount)
__SYSCALL(23, setuid)
__SYSCALL(24, getuid)
__SYSCALL(25, stime)
__SYSCALL_WITH_COMPAT(26, ptrace, compat_sys_ptrace)
__SYSCALL(27, alarm)
__SYSCALL(28, oldfstat)
__SYSCALL(29, pause)
__SYSCALL(30, utime)
__SYSCALL(33, access)
__SYSCALL(34, nice)
__SYSCALL(36, sync)
__SYSCALL(37, kill)
__SYSCALL(38, rename)
__SYSCALL(39, mkdir)
__SYSCALL(40, rmdir)
__SYSCALL(41, dup)
__SYSCALL(42, pipe)
__SYSCALL_WITH_COMPAT(43, times, compat_sys_times)
__SYSCALL(45, brk)
__SYSCALL(46, setgid)
__SYSCALL(47, getgid)
__SYSCALL(48, signal)
__SYSCALL(49, geteuid)
__SYSCALL(50, getegid)
__SYSCALL(51, acct)
__SYSCALL(52, umount2)
__SYSCALL_WITH_COMPAT(54, ioctl, compat_sys_ioctl)
__SYSCALL_WITH_COMPAT(55, fcntl, compat_sys_fcntl64)
__SYSCALL(57, setpgid)
__SYSCALL(59, oldolduname)
__SYSCALL(60, umask)
__SYSCALL(61, chroot)
__SYSCALL_WITH_COMPAT(62, ustat, compat_sys_ustat)
__SYSCALL(63, dup2)
__SYSCALL(64, getppid)
__SYSCALL(65, getpgrp)
__SYSCALL(66, setsid)
__SYSCALL_WITH_COMPAT(67, sigaction, compat_sys_sigaction)
__SYSCALL(68, sgetmask)
__SYSCALL(69, ssetmask)
__SYSCALL(70, setreuid)
__SYSCALL(71, setregid)
__SYSCALL(72, sigsuspend)
__SYSCALL_WITH_COMPAT(73, sigpending, compat_sys_sigpending)
__SYSCALL(74, sethostname)
__SYSCALL_WITH_COMPAT(75, setrlimit, compat_sys_setrlimit)
__SYSCALL_WITH_COMPAT(76, getrlimit, compat_sys_old_getrlimit)
__SYSCALL_WITH_COMPAT(77, getrusage, compat_sys_getrusage)
__SYSCALL_WITH_COMPAT(78, gettimeofday, compat_sys_gettimeofday)
__SYSCALL_WITH_COMPAT(79, settimeofday, compat_sys_settimeofday)
__SYSCALL(80, getgroups)
__SYSCALL(81, setgroups)
__SYSCALL_WITH_COMPAT(82, select, compat_sys_old_select)
__SYSCALL(83, symlink)
__SYSCALL(84, oldlstat)
__SYSCALL(85, readlink)
__SYSCALL(86, uselib)
__SYSCALL(87, swapon)
__SYSCALL(88, reboot)
__SYSCALL_WITH_COMPAT(89, readdir, compat_sys_old_readdir)
__SYSCALL_WITH_COMPAT(90, mmap, compat_sys_ia32_mmap)
__SYSCALL(91, munmap)
__SYSCALL_WITH_COMPAT(92, truncate, compat_sys_truncate)
__SYSCALL_WITH_COMPAT(93, ftruncate, compat_sys_ftruncate)
__SYSCALL(94, fchmod)
__SYSCALL(95, fchown)
__SYSCALL(96, getpriority)
__SYSCALL(97, setpriority)
__SYSCALL_WITH_COMPAT(99, statfs, compat_sys_statfs)
__SYSCALL_WITH_COMPAT(100, fstatfs, compat_sys_fstatfs)
__SYSCALL(101, ioperm)
__SYSCALL_WITH_COMPAT(102, socketcall, compat_sys_socketcall)
__SYSCALL(103, syslog)
__SYSCALL_WITH_COMPAT(104, setitimer, compat_sys_setitimer)
__SYSCALL_WITH_COMPAT(105, getitimer, compat_sys_getitimer)
__SYSCALL_WITH_COMPAT(106, stat, compat_sys_newstat)
__SYSCALL_WITH_COMPAT(107, lstat, compat_sys_newlstat)
__SYSCALL_WITH_COMPAT(108, fstat, compat_sys_newfstat)
__SYSCALL(109, olduname)
__SYSCALL(110, iopl)
__SYSCALL(111, vhangup)
__SYSCALL_WITH_COMPAT(113, vm86old, sys_ni_syscall)
__SYSCALL_WITH_COMPAT(114, wait4, compat_sys_wait4)
__SYSCALL(115, swapoff)
__SYSCALL_WITH_COMPAT(116, sysinfo, compat_sys_sysinfo)
__SYSCALL_WITH_COMPAT(117, ipc, compat_sys_ipc)
__SYSCALL(118, fsync)
__SYSCALL_WITH_COMPAT(119, sigreturn, compat_sys_sigreturn)
__SYSCALL_WITH_COMPAT(120, clone, compat_sys_ia32_clone)
__SYSCALL(121, setdomainname)
__SYSCALL(122, uname)
__SYSCALL(123, modify_ldt)
__SYSCALL(124, adjtimex)
__SYSCALL(125, mprotect)
__SYSCALL_WITH_COMPAT(126, sigprocmask, compat_sys_sigprocmask)
__SYSCALL(128, init_module)
__SYSCALL(129, delete_module)
__SYSCALL(131, quotactl)
__SYSCALL(132, getpgid)
__SYSCALL(133, fchdir)
__SYSCALL(134, bdflush)
__SYSCALL(135, sysfs)
__SYSCALL(136, personality)
__SYSCALL(138, setfsuid)
__SYSCALL(139, setfsgid)
__SYSCALL(140, _llseek)
__SYSCALL_WITH_COMPAT(141, getdents, compat_sys_getdents)
__SYSCALL_WITH_COMPAT(142, _newselect, compat_sys_select)
__SYSCALL(143, flock)
__SYSCALL(144, msync)
__SYSCALL(145, readv)
__SYSCALL(146, writev)
__SYSCALL(147, getsid)
__SYSCALL(148, fdatasync)
__SYSCALL(149, _sysctl)
__SYSCALL(150, mlock)
__SYSCALL(151, munlock)
__SYSCALL(152, mlockall)
__SYSCALL(153, munlockall)
__SYSCALL(154, sched_setparam)
__SYSCALL(155, sched_getparam)
__SYSCALL(156, sched_setscheduler)
__SYSCALL(157, sched_getscheduler)
__SYSCALL(158, sched_yield)
__SYSCALL(159, sched_get_priority_max)
__SYSCALL(160, sched_get_priority_min)
__SYSCALL(161, sched_rr_get_interval)
__SYSCALL(162, nanosleep)
__SYSCALL(163, mremap)
__SYSCALL(164, setresuid)
__SYSCALL(165, getresuid)
__SYSCALL_WITH_COMPAT(166, vm86, sys_ni_syscall)
__SYSCALL(168, poll)
__SYSCALL(170, setresgid)
__SYSCALL(171, getresgid)
__SYSCALL(172, prctl)
__SYSCALL_WITH_COMPAT(173, rt_sigreturn, compat_sys_rt_sigreturn)
__SYSCALL_WITH_COMPAT(174, rt_sigaction, compat_sys_rt_sigaction)
__SYSCALL_WITH_COMPAT(175, rt_sigprocmask, compat_sys_rt_sigprocmask)
__SYSCALL_WITH_COMPAT(176, rt_sigpending, compat_sys_rt_sigpending)
__SYSCALL_WITH_COMPAT(177, rt_sigtimedwait, compat_sys_rt_sigtimedwait_time32)
__SYSCALL_WITH_COMPAT(178, rt_sigqueueinfo, compat_sys_rt_sigqueueinfo)
__SYSCALL_WITH_COMPAT(179, rt_sigsuspend, compat_sys_rt_sigsuspend)
__SYSCALL(180, pread64)
__SYSCALL(181, pwrite64)
__SYSCALL(182, chown)
__SYSCALL(183, getcwd)
__SYSCALL(184, capget)
__SYSCALL(185, capset)
__SYSCALL_WITH_COMPAT(186, sigaltstack, compat_sys_sigaltstack)
__SYSCALL_WITH_COMPAT(187, sendfile, compat_sys_sendfile)
__SYSCALL(190, vfork)
__SYSCALL_WITH_COMPAT(191, ugetrlimit, compat_sys_getrlimit)
__SYSCALL(192, mmap2)
__SYSCALL(193, truncate64)
__SYSCALL(194, ftruncate64)
__SYSCALL_WITH_COMPAT(195, stat64, compat_sys_ia32_stat64)
__SYSCALL_WITH_COMPAT(196, lstat64, compat_sys_ia32_lstat64)
__SYSCALL_WITH_COMPAT(197, fstat64, compat_sys_ia32_fstat64)
__SYSCALL(198, lchown32)
__SYSCALL(199, getuid32)
__SYSCALL(200, getgid32)
__SYSCALL(201, geteuid32)
__SYSCALL(202, getegid32)
__SYSCALL(203, setreuid32)
__SYSCALL(204, setregid32)
__SYSCALL(205, getgroups32)
__SYSCALL(206, setgroups32)
__SYSCALL(207, fchown32)
__SYSCALL(208, setresuid32)
__SYSCALL(209, getresuid32)
__SYSCALL(210, setresgid32)
__SYSCALL(211, getresgid32)
__SYSCALL(212, chown32)
__SYSCALL(213, setuid32)
__SYSCALL(214, setgid32)
__SYSCALL(215, setfsuid32)
__SYSCALL(216, setfsgid32)
__SYSCALL(217, pivot_root)
__SYSCALL(218, mincore)
__SYSCALL(219, madvise)
__SYSCALL(220, getdents64)
__SYSCALL_WITH_COMPAT(221, fcntl64, compat_sys_fcntl64)
__SYSCALL(224, gettid)
__SYSCALL(225, readahead)
__SYSCALL(226, setxattr)
__SYSCALL(227, lsetxattr)
__SYSCALL(228, fsetxattr)
__SYSCALL(229, getxattr)
__SYSCALL(230, lgetxattr)
__SYSCALL(231, fgetxattr)
__SYSCALL(232, listxattr)
__SYSCALL(233, llistxattr)
__SYSCALL(234, flistxattr)
__SYSCALL(235, removexattr)
__SYSCALL(236, lremovexattr)
__SYSCALL(237, fremovexattr)
__SYSCALL(238, tkill)
__SYSCALL(239, sendfile64)
__SYSCALL(240, futex)
__SYSCALL_WITH_COMPAT(241, sched_setaffinity, compat_sys_sched_setaffinity)
__SYSCALL_WITH_COMPAT(242, sched_getaffinity, compat_sys_sched_getaffinity)
__SYSCALL(243, set_thread_area)
__SYSCALL(244, get_thread_area)
__SYSCALL_WITH_COMPAT(245, io_setup, compat_sys_io_setup)
__SYSCALL(246, io_destroy)
__SYSCALL(247, io_getevents)
__SYSCALL_WITH_COMPAT(248, io_submit, compat_sys_io_submit)
__SYSCALL(249, io_cancel)
__SYSCALL(250, fadvise64)
__SYSCALL(252, exit_group)
__SYSCALL_WITH_COMPAT(253, lookup_dcookie, compat_sys_lookup_dcookie)
__SYSCALL(254, epoll_create)
__SYSCALL(255, epoll_ctl)
__SYSCALL(256, epoll_wait)
__SYSCALL(257, remap_file_pages)
__SYSCALL(258, set_tid_address)
__SYSCALL_WITH_COMPAT(259, timer_create, compat_sys_timer_create)
__SYSCALL(260, timer_settime)
__SYSCALL(261, timer_gettime)
__SYSCALL(262, timer_getoverrun)
__SYSCALL(263, timer_delete)
__SYSCALL(264, clock_settime)
__SYSCALL(265, clock_gettime)
__SYSCALL(266, clock_getres)
__SYSCALL(267, clock_nanosleep)
__SYSCALL_WITH_COMPAT(268, statfs64, compat_sys_statfs64)
__SYSCALL_WITH_COMPAT(269, fstatfs64, compat_sys_fstatfs64)
__SYSCALL(270, tgkill)
__SYSCALL(271, utimes)
__SYSCALL(272, fadvise64_64)
__SYSCALL(274, mbind)
__SYSCALL(275, get_mempolicy)
__SYSCALL(276, set_mempolicy)
__SYSCALL_WITH_COMPAT(277, mq_open, compat_sys_mq_open)
__SYSCALL(278, mq_unlink)
__SYSCALL(279, mq_timedsend)
__SYSCALL(280, mq_timedreceive)
__SYSCALL_WITH_COMPAT(281, mq_notify, compat_sys_mq_notify)
__SYSCALL_WITH_COMPAT(282, mq_getsetattr, compat_sys_mq_getsetattr)
__SYSCALL_WITH_COMPAT(283, kexec_load, compat_sys_kexec_load)
__SYSCALL_WITH_COMPAT(284, waitid, compat_sys_waitid)
__SYSCALL(286, add_key)
__SYSCALL(287, request_key)
__SYSCALL_WITH_COMPAT(288, keyctl, compat_sys_keyctl)
__SYSCALL(289, ioprio_set)
__SYSCALL(290, ioprio_get)
__SYSCALL(291, inotify_init)
__SYSCALL(292, inotify_add_watch)
__SYSCALL(293, inotify_rm_watch)
__SYSCALL(294, migrate_pages)
__SYSCALL_WITH_COMPAT(295, openat, compat_sys_openat)
__SYSCALL(296, mkdirat)
__SYSCALL(297, mknodat)
__SYSCALL(298, fchownat)
__SYSCALL(299, futimesat)
__SYSCALL_WITH_COMPAT(300, fstatat64, compat_sys_ia32_fstatat64)
__SYSCALL(301, unlinkat)
__SYSCALL(302, renameat)
__SYSCALL(303, linkat)
__SYSCALL(304, symlinkat)
__SYSCALL(305, readlinkat)
__SYSCALL(306, fchmodat)
__SYSCALL(307, faccessat)
__SYSCALL_WITH_COMPAT(308, pselect6, compat_sys_pselect6_time32)
__SYSCALL_WITH_COMPAT(309, ppoll, compat_sys_ppoll_time32)
__SYSCALL(310, unshare)
__SYSCALL_WITH_COMPAT(311, set_robust_list, compat_sys_set_robust_list)
__SYSCALL_WITH_COMPAT(312, get_robust_list, compat_sys_get_robust_list)
__SYSCALL(313, splice)
__SYSCALL(314, sync_file_range)
__SYSCALL(315, tee)
__SYSCALL(316, vmsplice)
__SYSCALL(317, move_pages)
__SYSCALL(318, getcpu)
__SYSCALL(319, epoll_pwait)
__SYSCALL(320, utimensat)
__SYSCALL_WITH_COMPAT(321, signalfd, compat_sys_signalfd)
__SYSCALL(322, timerfd_create)
__SYSCALL(323, eventfd)
__SYSCALL(324, fallocate)
__SYSCALL(325, timerfd_settime)
__SYSCALL(326, timerfd_gettime)
__SYSCALL_WITH_COMPAT(327, signalfd4, compat_sys_signalfd4)
__SYSCALL(328, eventfd2)
__SYSCALL(329, epoll_create1)
__SYSCALL(330, dup3)
__SYSCALL(331, pipe2)
__SYSCALL(332, inotify_init1)
__SYSCALL_WITH_COMPAT(333, preadv, compat_sys_preadv)
__SYSCALL_WITH_COMPAT(334, pwritev, compat_sys_pwritev)
__SYSCALL_WITH_COMPAT(335, rt_tgsigqueueinfo, compat_sys_rt_tgsigqueueinfo)
__SYSCALL(336, perf_event_open)
__SYSCALL_WITH_COMPAT(337, recvmmsg, compat_sys_recvmmsg_time32)
__SYSCALL(338, fanotify_init)
__SYSCALL_WITH_COMPAT(339, fanotify_mark, compat_sys_fanotify_mark)
__SYSCALL(340, prlimit64)
__SYSCALL(341, name_to_handle_at)
__SYSCALL_WITH_COMPAT(342, open_by_handle_at, compat_sys_open_by_handle_at)
__SYSCALL(343, clock_adjtime)
__SYSCALL(344, syncfs)
__SYSCALL_WITH_COMPAT(345, sendmmsg, compat_sys_sendmmsg)
__SYSCALL(346, setns)
__SYSCALL(347, process_vm_readv)
__SYSCALL(348, process_vm_writev)
__SYSCALL(349, kcmp)
__SYSCALL(350, finit_module)
__SYSCALL(351, sched_setattr)
__SYSCALL(352, sched_getattr)
__SYSCALL(353, renameat2)
__SYSCALL(354, seccomp)
__SYSCALL(355, getrandom)
__SYSCALL(356, memfd_create)
__SYSCALL(357, bpf)
__SYSCALL_WITH_COMPAT(358, execveat, compat_sys_execveat)
__SYSCALL(359, socket)
__SYSCALL(360, socketpair)
__SYSCALL(361, bind)
__SYSCALL(362, connect)
__SYSCALL(363, listen)
__SYSCALL(364, accept4)
__SYSCALL_WITH_COMPAT(365, getsockopt, sys_getsockopt)
__SYSCALL_WITH_COMPAT(366, setsockopt, sys_setsockopt)
__SYSCALL(367, getsockname)
__SYSCALL(368, getpeername)
__SYSCALL(369, sendto)
__SYSCALL_WITH_COMPAT(370, sendmsg, compat_sys_sendmsg)
__SYSCALL_WITH_COMPAT(371, recvfrom, compat_sys_recvfrom)
__SYSCALL_WITH_COMPAT(372, recvmsg, compat_sys_recvmsg)
__SYSCALL(373, shutdown)
__SYSCALL(374, userfaultfd)
__SYSCALL(375, membarrier)
__SYSCALL(376, mlock2)
__SYSCALL(377, copy_file_range)
__SYSCALL_WITH_COMPAT(378, preadv2, compat_sys_preadv2)
__SYSCALL_WITH_COMPAT(379, pwritev2, compat_sys_pwritev2)
__SYSCALL(380, pkey_mprotect)
__SYSCALL(381, pkey_alloc)
__SYSCALL(382, pkey_free)
__SYSCALL(383, statx)
__SYSCALL_WITH_COMPAT(384, arch_prctl, compat_sys_arch_prctl)
__SYSCALL_WITH_COMPAT(385, io_pgetevents, compat_sys_io_pgetevents)
__SYSCALL(386, rseq)
__SYSCALL(393, semget)
__SYSCALL_WITH_COMPAT(394, semctl, compat_sys_semctl)
__SYSCALL(395, shmget)
__SYSCALL_WITH_COMPAT(396, shmctl, compat_sys_shmctl)
__SYSCALL_WITH_COMPAT(397, shmat, compat_sys_shmat)
__SYSCALL(398, shmdt)
__SYSCALL(399, msgget)
__SYSCALL_WITH_COMPAT(400, msgsnd, compat_sys_msgsnd)
__SYSCALL_WITH_COMPAT(401, msgrcv, compat_sys_msgrcv)
__SYSCALL_WITH_COMPAT(402, msgctl, compat_sys_msgctl)
__SYSCALL(403, clock_gettime64)
__SYSCALL(404, clock_settime64)
__SYSCALL(405, clock_adjtime64)
__SYSCALL(406, clock_getres_time64)
__SYSCALL(407, clock_nanosleep_time64)
__SYSCALL(408, timer_gettime64)
__SYSCALL(409, timer_settime64)
__SYSCALL(410, timerfd_gettime64)
__SYSCALL(411, timerfd_settime64)
__SYSCALL(412, utimensat_time64)
__SYSCALL_WITH_COMPAT(413, pselect6_time64, compat_sys_pselect6_time64)
__SYSCALL_WITH_COMPAT(414, ppoll_time64, compat_sys_ppoll_time64)
__SYSCALL(416, io_pgetevents_time64)
__SYSCALL_WITH_COMPAT(417, recvmmsg_time64, compat_sys_recvmmsg_time64)
__SYSCALL(418, mq_timedsend_time64)
__SYSCALL(419, mq_timedreceive_time64)
__SYSCALL(420, semtimedop_time64)
__SYSCALL_WITH_COMPAT(421, rt_sigtimedwait_time64, compat_sys_rt_sigtimedwait_time64)
__SYSCALL(422, futex_time64)
__SYSCALL(423, sched_rr_get_interval_time64)
__SYSCALL(424, pidfd_send_signal)
__SYSCALL(425, io_uring_setup)
__SYSCALL(426, io_uring_enter)
__SYSCALL(427, io_uring_register)
__SYSCALL(428, open_tree)
__SYSCALL(429, move_mount)
__SYSCALL(430, fsopen)
__SYSCALL(431, fsconfig)
__SYSCALL(432, fsmount)
__SYSCALL(433, fspick)
__SYSCALL(434, pidfd_open)
__SYSCALL(435, clone3)
__SYSCALL(436, close_range)
__SYSCALL(437, openat2)
__SYSCALL(438, pidfd_getfd)
__SYSCALL(439, faccessat2)
__SYSCALL(440, process_madvise)
__SYSCALL_WITH_COMPAT(441, epoll_pwait2, compat_sys_epoll_pwait2)
__SYSCALL(442, mount_setattr)
__SYSCALL(443, quotactl_fd)
__SYSCALL(444, landlock_create_ruleset)
__SYSCALL(445, landlock_add_rule)
__SYSCALL(446, landlock_restrict_self)
__SYSCALL(447, memfd_secret)
__SYSCALL(448, process_mrelease)
__SYSCALL(449, futex_waitv)
__SYSCALL(450, set_mempolicy_home_node)
